# Generated by Django 4.2.27 on 2025-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('team_country', models.CharField(max_length=50)),
                ('team_league', models.CharField(max_length=50)),
                ('all_bets', models.DecimalField(decimal_places=2, max_digits=6)),
                ('extra_bets', models.DecimalField(decimal_places=2, max_digits=6)),
                ('no_draw', models.IntegerField()),
            ],
        ),
    ]
