# Generated by Django 4.2.27 on 2026-10-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingvalue',
            name='all_bets_snapshot_end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trackingvalue',
            name='all_bets_snapshot_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trackingvalue',
            name='category',
            field=models.CharField(choices=[('PROFIT', 'Profit'), ('BET', 'Bet'), ('PLUS_EARNED', 'Plus earned'), ('PLUS_USED', 'Plus used'), ('ALL_BETS_SNAPSHOT_START', 'All bets start of week'), ('ALL_BETS_SNAPSHOT_END', 'All bets end of week')], db_index=True, max_length=30),
        ),
    ]
