# Generated by Django 4.2.27 on 2025-12-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
