# Generated by Django 4.2.27 on 2026-10-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trackingvalue_all_bets_snapshot_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingvalue',
            name='all_bets_snapshot_end',
        ),
        migrations.RemoveField(
            model_name='trackingvalue',
            name='all_bets_snapshot_start',
        ),
    ]
