# Generated by Django 4.2.27 on 2025-12-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_team_id_alter_team_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_country',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last_played_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='all_bets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='extra_bets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='no_draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('in_season', models.BooleanField(default=False)),
                ('season_start', models.DateField(blank=True, default=None, null=True)),
                ('season_end', models.DateField(blank=True, default=None, null=True)),
                ('season_year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('last_updated_date', models.DateField(blank=True, default=None, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_id', models.IntegerField()),
                ('away_id', models.IntegerField()),
                ('home_team_name', models.CharField(max_length=50)),
                ('away_team_name', models.CharField(max_length=50)),
                ('home_team_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_team_bet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home_team_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_team_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home_team_plus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_team_plus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_played', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('season', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.league')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.country'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.league'),
        ),
    ]
