# Generated by Django 4.2.27 on 2026-01-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_rename_team_id_team_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bet', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum bet', max_digits=4, null=True)),
                ('avg_perc_draw', models.DecimalField(blank=True, decimal_places=2, help_text='Average percentage draw per round', max_digits=2, null=True)),
                ('rounds_for_earning_back', models.IntegerField(default=0, help_text='Round to earn back')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='fixture',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
