# Generated by Django 4.2.27 on 2026-01-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings_alter_fixture_options_alter_fixture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team_bet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team_bet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='avg_perc_draw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average percentage draw per round', max_digits=4, null=True),
        ),
    ]
