# Generated by Django 4.2.27 on 2026-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fixture_away_team_bet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name', models.CharField(max_length=50)),
                ('away_team_name', models.CharField(max_length=50)),
                ('home_team_bet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('away_team_bet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('home_team_profit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('away_team_profit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('home_team_plus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('away_team_plus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('is_draw', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('league_name', models.CharField(max_length=100)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('PROFIT', 'Profit'), ('BET', 'Bet'), ('PLUS', 'Plus')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'category')},
            },
        ),
    ]
