# Generated by Django 4.2.27 on 2026-01-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_archivedfixture_trackingvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingvalue',
            name='category',
            field=models.CharField(choices=[('PROFIT', 'Profit'), ('BET', 'Bet'), ('PLUS_EARNED', 'Plus earned'), ('PLUS_USED', 'Plus used')], max_length=11),
        ),
    ]
