# Generated by Django 4.2.27 on 2026-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trackingvalue_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedfixture',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='away_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='home_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
