# Generated by Django 4.2.27 on 2026-02-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_archivedfixture_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForRecover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added_to_recover', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.IntegerField(db_index=True)),
                ('team_name', models.CharField(max_length=50)),
                ('bets_writen_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bets_recovered', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fixtures_played', models.IntegerField(default=0)),
                ('fixtures_recovered', models.IntegerField(default=0)),
                ('date_recovered', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_recovered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='away_team_for_recovery',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='entry_for_recover',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='home_team_for_recovery',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team_for_recovery',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='fixture',
            name='entry_for_recover',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_for_recovery',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
    ]
