# Generated by Django 4.2.27 on 2026-02-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_forrecover_archivedfixture_away_team_for_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forrecover',
            name='plus_used_to_recover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
