# Generated by Django 4.2.27 on 2026-02-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_forrecover_plus_used_to_recover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='entry_for_recover',
            new_name='away_team_entry_for_recovery_with_bet',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='away_team_for_recovery',
            new_name='away_team_money_to_recover',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='home_team_for_recovery',
            new_name='away_team_plus_used_to_recover',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team_entry_for_recovery_with_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_entry_for_recovery_with_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_entry_for_recovery_with_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_money_to_recover',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_plus_used_to_recover',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
    ]
