# Generated by Django 4.2.27 on 2026-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_entry_for_recover_fixture_away_team_entry_for_recovery_with_bet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedfixture',
            old_name='entry_for_recover',
            new_name='away_team_entry_for_recovery_with_bet',
        ),
        migrations.RenameField(
            model_name='archivedfixture',
            old_name='away_team_for_recovery',
            new_name='away_team_money_to_recover',
        ),
        migrations.RenameField(
            model_name='archivedfixture',
            old_name='home_team_for_recovery',
            new_name='home_team_money_to_recover',
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='home_team_entry_for_recovery_with_bet',
            field=models.IntegerField(default=0),
        ),
    ]
