# Generated by Django 4.2.27 on 2026-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_entry_for_recover_archivedfixture_away_team_entry_for_recovery_with_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='use_plus_for_recover',
            field=models.BooleanField(default=True),
        ),
    ]
