# Generated by Django 4.2.27 on 2026-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_settings_use_plus_for_recover'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedfixture',
            name='away_team_entry_for_recovery_with_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='away_team_plus_used_to_recover',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='home_team_entry_for_recovery_with_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='home_team_plus_used_to_recover',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=7),
        ),
    ]
