# Generated by Django 4.2.27 on 2026-03-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_archivedfixture_away_team_entry_for_recovery_with_plus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='api_sport_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecoverFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(db_index=True)),
                ('value', models.IntegerField()),
                ('value_type', models.CharField(choices=[('bet', 'Bet'), ('plus', 'Plus'), ('manual_plus', 'Manual Plus')], max_length=12)),
                ('for_recover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_for_recover', to='core.forrecover')),
            ],
            options={
                'indexes': [models.Index(fields=['fixture_id'], name='core_recove_fixture_5e0963_idx'), models.Index(fields=['for_recover'], name='core_recove_for_rec_38d31b_idx')],
            },
        ),
    ]
