# Generated by Django 4.2.27 on 2026-03-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fixture_api_sport_id_fixture_fixture_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recoverfixture',
            name='core_recove_fixture_5e0963_idx',
        ),
        migrations.RenameField(
            model_name='forrecover',
            old_name='team_id',
            new_name='old_team_id',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='away_team_entry_for_recovery_with_plus',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='away_team_plus_used_to_recover',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team_entry_for_recovery_with_plus',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team_plus_used_to_recover',
        ),
        migrations.RemoveField(
            model_name='recoverfixture',
            name='fixture_id',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team_plus_used_for_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_plus_used_for_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forrecover',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='recoverfixture',
            name='fixture',
            field=models.ForeignKey(blank=True, db_column='fixture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recover_fixtures', to='core.fixture', to_field='fixture_id'),
        ),
        migrations.AddField(
            model_name='recoverfixture',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='api_sport_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='fixture_id',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
        migrations.AddIndex(
            model_name='recoverfixture',
            index=models.Index(fields=['fixture'], name='core_recove_fixture_5e0963_idx'),
        ),
    ]
