# Generated by Django 4.2.27 on 2026-03-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_recoverfixture_core_recove_fixture_5e0963_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='away_team_plus_used_for_recovery',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='home_team_plus_used_for_recovery',
        ),
    ]
