# Generated by Django 4.2.27 on 2026-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_fixture_away_team_plus_used_for_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_team_plus_used_for_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team_plus_used_for_recovery',
            field=models.BooleanField(default=False),
        ),
    ]
