# Generated by Django 4.2.27 on 2026-03-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fixture_away_team_plus_used_for_recovery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forrecover',
            name='old_team_id',
        ),
        migrations.RemoveField(
            model_name='forrecover',
            name='team',
        ),
    ]
