# Generated by Django 4.2.27 on 2026-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_forrecover_old_team_id_remove_forrecover_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='forrecover',
            name='team_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
