# Generated by Django 4.2.27 on 2026-03-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_forrecover_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forrecover',
            name='team_id',
        ),
        migrations.AddField(
            model_name='forrecover',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
    ]
