# Generated by Django 4.2.27 on 2026-03-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_forrecover_team_id_forrecover_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverfixture',
            name='team_id',
        ),
    ]
