# Generated by Django 4.2.27 on 2026-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_recoverfixture_team_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecoverFixture',
        ),
    ]
