# Generated by Django 4.2.27 on 2026-03-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_recoverfixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('value_type', models.CharField(choices=[('bet', 'Bet'), ('plus', 'Plus'), ('manual_plus', 'Manual Plus')], max_length=12)),
                ('fixture', models.ForeignKey(blank=True, db_column='fixture_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recover_fixtures', to='core.fixture', to_field='fixture_id')),
                ('for_recover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_for_recover', to='core.forrecover')),
            ],
            options={
                'indexes': [models.Index(fields=['fixture'], name='core_recove_fixture_5e0963_idx'), models.Index(fields=['for_recover'], name='core_recove_for_rec_38d31b_idx')],
            },
        ),
    ]
