# Generated by Django 4.2.27 on 2026-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_recoverfixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedfixture',
            name='away_team_entry_for_recovery_with_plus',
        ),
        migrations.RemoveField(
            model_name='archivedfixture',
            name='away_team_plus_used_to_recover',
        ),
        migrations.RemoveField(
            model_name='archivedfixture',
            name='home_team_entry_for_recovery_with_plus',
        ),
        migrations.RemoveField(
            model_name='archivedfixture',
            name='home_team_plus_used_to_recover',
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='api_sport_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='away_team_plus_used_for_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='home_team_plus_used_for_recovery',
            field=models.BooleanField(default=False),
        ),
    ]
