# Generated by Django 4.2.27 on 2026-03-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_archivedfixture_away_team_entry_for_recovery_with_plus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedfixture',
            name='fixture_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
