# Generated by Django 4.2.27 on 2026-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_archivedfixture_fixture_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recoverfixture',
            name='core_recove_fixture_5e0963_idx',
        ),
        migrations.RemoveField(
            model_name='recoverfixture',
            name='fixture',
        ),
        migrations.AddField(
            model_name='recoverfixture',
            name='fixture_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='recoverfixture',
            index=models.Index(fields=['fixture_id'], name='core_recove_fixture_5e0963_idx'),
        ),
    ]
