# Generated by Django 4.2.27 on 2026-03-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_recoverfixture_core_recove_fixture_5e0963_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverfixture',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recoverfixture',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
    ]
