# Generated by Django 4.2.27 on 2026-03-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_recoverfixture_date_recoverfixture_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedfixture',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.country'),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='is_played',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.league'),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='season',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedfixture',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
