# Generated by Django 4.2.27 on 2026-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_archivedfixture_country_archivedfixture_is_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.FileField(blank=True, null=True, upload_to='countries/flags/'),
        ),
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/logos/'),
        ),
    ]
