# Generated by Django 4.2.27 on 2026-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_country_flag_league_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingvalue',
            name='category',
            field=models.CharField(choices=[('PROFIT', 'Profit'), ('BET', 'Bet'), ('PLUS_EARNED', 'Plus earned'), ('PLUS_USED', 'Plus used')], db_index=True, max_length=11),
        ),
    ]
