# Generated by Django 4.2.27 on 2026-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_trackingvalue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forrecover',
            name='plus_used_manual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
