# Generated by Django 4.2.27 on 2026-04-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_forrecover_plus_used_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverfixture',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
