# Generated by Django 4.2.27 on 2026-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_recoverfixture_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverfixture',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
