# Generated by Django 4.2.27 on 2026-04-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_recoverfixture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
    ]
