# Generated by Django 4.2.27 on 2026-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_pendingimport_externalmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='all_bets',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
