# Generated by Django 4.2.27 on 2026-05-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_team_all_bets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='no_draw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
