# Generated by Django 4.2.27 on 2026-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_team_extra_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
