# Generated by Django 4.2.27 on 2026-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_team_is_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedfixture',
            name='league_round',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='league_round',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
