# Generated by Django 4.2.27 on 2026-05-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingimport',
            name='are_fixtures_imported',
            field=models.BooleanField(default=False),
        ),
    ]
