# Generated by Django 4.2.27 on 2026-05-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0043_pendingimport_are_fixtures_imported'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='externalmapping',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Specify if this external name is country-specific (e.g., Premier League)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AlterUniqueTogether(
            name='externalmapping',
            unique_together={('external_name', 'content_type', 'country')},
        ),
    ]
