# Generated by Django 4.2.27 on 2026-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_externalmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='avg_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average coefficient', max_digits=6, null=True),
        ),
    ]
