# Generated by Django 4.2.27 on 2026-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_settings_avg_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedfixture',
            name='sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fixture',
            name='sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
