# Generated by Django 4.2.27 on 2026-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_archivedfixture_sources_fixture_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='hierarchy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
