# Generated by Django 4.2.27 on 2026-08-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_league_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='regular_league',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='has_league_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TeamLeagueHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Promotion', 'Promotion'), ('Relegation', 'Relegation')], max_length=20)),
                ('showed_ui', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_promoted_relegated_to', to='core.league')),
                ('old_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams_promoted_relegated_from', to='core.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_histories', to='core.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
