"""
Django settings for Server project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the .env file from your project root
load_dotenv(os.path.join(BASE_DIR, '.env'))

# 1. Get the toggle from the environment, default to False if not found
IS_PRODUCTION = os.getenv('IS_PRODUCTION', 'False') == 'True'

# Axes Configuration (shared)
AXES_FAILURE_LIMIT = 5  # Lock out after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Wait 1 hour before trying again
AXES_LOCKOUT_URL = '/locked-out/'
# AXES_LOCKOUT_TEMPLATE = 'lockout.html'  # Show a custom "You are locked out" page
AXES_RESET_ON_SUCCESS = True  # Reset failures if they finally get it right
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
# This ensures the lockout check happens on the GET request too (to not show login page)
# AXES_ONLY_USER_FAILURES = False
# Record every failed login attempt in the database immediately
AXES_ENABLE_ACCESS_FAILURE_LOG = True
# Optional: If you want to see SUCCESSFUL logins too
AXES_ENABLE_ACCESS_LOG = True
AXES_ONLY_ADMIN_SITE = False
# AXES_LOCKOUT_CALLABLE = 'axes.helpers.get_client_username'
# AXES_LOCKOUT_CALLABLE = 'axes.handlers.proxy.AxesProxyHandler'

# 3. Environmental Logic
if IS_PRODUCTION:
    # PRODUCTION: Behind Nginx/Load Balancer
    AXES_IPWARE_PROXY_COUNT = int(os.getenv('AXES_IPWARE_PROXY_COUNT', 1))
    AXES_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']

    # Other Prod-only settings
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False
    SECURE_SSL_REDIRECT = True
    # Pull from .env: e.g., "mydomain.com,www.mydomain.com"
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

    # Extra Production Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    # DEVELOPMENT: Local machine
    AXES_IPWARE_PROXY_COUNT = 0
    DEBUG = True
    SECURE_SSL_REDIRECT = False
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

SECRET_KEY = os.getenv('SECRET_KEY')

# Protects the endpoints
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'axes',
    'constance',
    'constance.backends.database',
    'corsheaders',
]

# Tell Constance to store data in your Postgres DB
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

# Define your "Manual" settings here
CONSTANCE_CONFIG = {
    'MIN_BET': (Decimal("0.10"), 'Minimum bet allowed per round', Decimal),
    'AVG_PERC_DRAW': (Decimal("22.00"), 'Average percentage draw per round', Decimal),
    'ROUNDS_FOR_EARNING_BACK': (3, 'Number of rounds to earn back investment', int),
}
# Optional: Group them in the Admin UI for better looks
CONSTANCE_CONFIG_FIELDSETS = {
    'Betting Settings': ('MIN_BET', 'AVG_PERC_DRAW'),
    'Stats Settings': ('ROUNDS_FOR_EARNING_BACK',),
}

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # Axes must be first!
    'axes.backends.AxesStandaloneBackend',
    # Default Django authentication
    'django.contrib.auth.backends.ModelBackend',
]

CORS_ALLOWED_ORIGINS = [
    "chrome-extension://cknppenmojidgomhkfnjdhnaaimafaki",
]

ROOT_URLCONF = 'Server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'server_user'),
        'PASSWORD': os.getenv('DB_PASSWORD'),  # Pulled from .env
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True
TIME_ZONE = 'Europe/Sofia'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'

# This tells Django to look for a 'static' folder in your root directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# This is for production (when you run collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = True

ADMIN_URL = os.getenv('ADMIN_URL', 'admin')  # Fallback to 'admin' if not set

# Where to send users to log in
LOGIN_URL = 'login'

# Where to send users after they log in
LOGIN_REDIRECT_URL = 'dashboard'

# Where to send users after they log out
LOGOUT_REDIRECT_URL = 'login'

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
